# Generated by Django 3.1.6 on 2021-02-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='studentid',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
