# Generated by Django 3.1.7 on 2021-03-30 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.CharField(max_length=200)),
                ('department_name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=5000)),
            ],
            options={
                'db_table': 'departments',
                'ordering': ['department_id'],
            },
        ),
        migrations.CreateModel(
            name='UserBaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-registered_at', '-name'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('userbasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='classroom.userbasemodel')),
                ('teacher_id', models.CharField(max_length=200)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.department')),
            ],
            options={
                'db_table': 'teachers',
            },
            bases=('classroom.userbasemodel',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('userbasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='classroom.userbasemodel')),
                ('student_id', models.CharField(max_length=200)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.department')),
            ],
            options={
                'db_table': 'students',
            },
            bases=('classroom.userbasemodel',),
        ),
    ]
